# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testRx' do
	pod 'RxSwift', '6.6.0'
	pod 'RxCocoa', '6.6.0'
	pod 'RxRelay', '6.6.0'
	pod 'RxDataSources', '~> 5.0'
end
